import "./globals.css";
import AnimatedBackground from "./AnimatedBackground";
import ClientWrapper from "./ClientWrapper";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
// import AiChatbot from "@/components/AiChatbot";

export const metadata = {
  title: "BDB Self Service Portal",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        {/* Global Animated Background */}
        <AnimatedBackground />

        {/* Navbar */}
        <Navbar />

        {/* Main content wrapper */}
        <div className="mainComponent">
          <ClientWrapper>{children}</ClientWrapper>
        </div>

        {/* Footer */}
        <Footer />
      </body>
    </html>
  );
}
